-- General Configuration

require("myconfig.plugins")
require("myconfig.colorscheme")
require("myconfig.vim_config")
require("myconfig.telescope")
require("myconfig.copilot")
require("myconfig.capabilities")
require("myconfig.cmp")
require("myconfig.null_ls")
require("myconfig.on_attach")
require("myconfig.diagnostic")
require("myconfig.status_line")
require("myconfig.treesitter")
require("myconfig.lsp")
require("myconfig.tree")
